# Project: ÂÃÐÐ1
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = graph.o money.o time.o time+money.o main.o print.o
LINKOBJ  = graph.o money.o time.o time+money.o main.o print.o
LIBS     = -L"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc libegg22.a -m32 -g3
INCS     = -I"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/lenovo/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = ÂÃÐÐ1.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

graph.o: graph.cpp
	$(CPP) -c graph.cpp -o graph.o $(CXXFLAGS)

money.o: money.cpp
	$(CPP) -c money.cpp -o money.o $(CXXFLAGS)

time.o: time.cpp
	$(CPP) -c time.cpp -o time.o $(CXXFLAGS)

time+money.o: time+money.cpp
	$(CPP) -c time+money.cpp -o time+money.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

print.o: print.cpp
	$(CPP) -c print.cpp -o print.o $(CXXFLAGS)
